pull reqest
MaximMaslovVik/15_sprint pull request #1
Opened 2020-02-01 21:48 UTC by MaximMaslovVik

2020-02-02 07:16 UTC, aarefiev reviewed
К сожалению работу не удалось проверить детально. По ссылкам, указанным в README.md не удалось зайти на сервер, а по заданию, сервер должен быть доступен по доменному имени и по ip по протоколам http и https. Также сервер не удалось запустить локально. Ниже я привел список ошибок, которые были найдены в ходе изучения кода и попыток запуска сервера локально.

**Нужно исправить:**
1. По ссылкам, указанным в README.md не удалось зайти на сервер по IP и доменному имени.
2. Ошибки линтинга.
3. Сервер не запускается.
4. Валидация поля `avatar` не соответствует схеме модели.
5. Валидация поля `password` не соответствует схеме модели.
6. Некорректная валидация для роута `/signin`.
7. Не назначена валидация для роута `GET /users/:userId`.
8. Не назначена валидация для роутов `/cards`.
9. Нет централизованной обработки ошибок.

---

**Развернутый комментарий к ошибке "Ошибки линтинга":**

При попытке запустить команду линтинга `npx eslint --ext .js .` линтер сообщает об ошибках:
```bash
$ npx eslint --ext .js .
...
✖ 24 problems (24 errors, 0 warnings)
  15 errors and 0 warnings potentially fixable with the `--fix` option.
```
_часть вывода я намеренно опустил для экономии места_

Ожидаемый результат - ошибок маркерованных **error** нет (**warning** допускается).

**Развернутый комментарий к ошибке "Нет централизованной обработки ошибок":**
В этой практике обработка ошибок должна быть вынесена в отдельный мидлвэр. Который будет на основе ошибки отправлять ответ на сервер.
Вместо подобного:
https://github.com/MaximMaslovVik/15_sprint/blob/7795405d4cfb6d0f4c59987d2d17daace09498a1/controllers/cards.js#L7
или
https://github.com/MaximMaslovVik/15_sprint/blob/7795405d4cfb6d0f4c59987d2d17daace09498a1/controllers/cards.js#L11
Нужно создать ошибки `NotFoundError` и `InternalError` и возвращать их через [`next()`](https://expressjs.com/ru/guide/using-middleware.html).

2020-02-02 07:16 UTC, aarefiev commented on app.js
> +const { celebrate, Joi, errors } = require('celebrate');
Нужно исправить: сервер не запускается.
```bash
internal/modules/cjs/loader.js:964
    throw err;
    ^

Error: Cannot find module 'celebrate'
Require stack:
- ~/15_sprint/app.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:961:17)
    at Function.Module._load (internal/modules/cjs/loader.js:854:27)
    at Module.require (internal/modules/cjs/loader.js:1023:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (~/15_sprint/app.js:5:36)
    at Module._compile (internal/modules/cjs/loader.js:1128:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
    at Module.load (internal/modules/cjs/loader.js:983:32)
    at Function.Module._load (internal/modules/cjs/loader.js:891:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '~/15_sprint/app.js' ]
}
```

Ошибка говорит о том, что модуль `celebrate` не найден в списке установленных модулей. Судя по содержимому  зависимостей `package.json` так и есть. Нужно его добавить.

2020-02-02 07:16 UTC, aarefiev commented on app.js
> +    avatar: Joi.string().required(),
Нужно исправить: валидация поля `avatar` не соответствует схеме модели.
В модели `User` поле `avatar` проверяется на соответствие выражению:
https://github.com/MaximMaslovVik/15_sprint/blob/39b375ef04ef4bde4276597bcc4dcbd69bdfe0ca/models/user.js#L5
https://github.com/MaximMaslovVik/15_sprint/blob/39b375ef04ef4bde4276597bcc4dcbd69bdfe0ca/models/user.js#L22

2020-02-02 07:16 UTC, aarefiev commented on app.js
> +    password: Joi.string().required().min(8),
Нужно исправить: валидация поля `password` не соответствует схеме модели.
В модели `User` поле `password` должно составлять минимум 8 символов:
https://github.com/MaximMaslovVik/15_sprint/blob/39b375ef04ef4bde4276597bcc4dcbd69bdfe0ca/models/user.js#L26-L29

2020-02-02 07:16 UTC, aarefiev commented on app.js
> +    password: Joi.string().required(),
Нужно исправить: некорректная валидация для роута `/signin`.
Здесь несколько ошибок:
1. Роут ожидает только `email` и `password` в параметрах запроса:
https://github.com/MaximMaslovVik/15_sprint/blob/39b375ef04ef4bde4276597bcc4dcbd69bdfe0ca/controllers/users.js#L46-L47
Нужно удалить лишние, те `name`, `about`, `avatar`.

2. Схема поля `password` не соответствует схеме модели:
https://github.com/MaximMaslovVik/15_sprint/blob/39b375ef04ef4bde4276597bcc4dcbd69bdfe0ca/models/user.js#L26-L29
В частности не хватает ограничения по длине `.min(10)`.

2020-02-02 07:16 UTC, aarefiev commented on app.js
>  app.use('/', users);
Нужно исправить: не назначена валидация для роута `GET /users/:userId`.
Роут:
https://github.com/MaximMaslovVik/15_sprint/blob/39b375ef04ef4bde4276597bcc4dcbd69bdfe0ca/routes/users.js#L5
Этот роут получает `userId` пользователя в параметрах запроса (`params`), этот `userId` не обычный, его нужно также проверять. Для этого лучше использовать модуль [joi-objectid](https://www.npmjs.com/package/joi-objectid).

Также нужно удалить повторное назначение роутов для `/signup` и `/signin` во избежание ошибок:
https://github.com/MaximMaslovVik/15_sprint/blob/39b375ef04ef4bde4276597bcc4dcbd69bdfe0ca/routes/users.js#L6-L7

2020-02-02 07:16 UTC, aarefiev commented on app.js
>  app.use('/', cards);
Нужно исправить: не назначена валидация для роутов `/cards`.
1. Роут  `POST /cards`:
https://github.com/MaximMaslovVik/15_sprint/blob/39b375ef04ef4bde4276597bcc4dcbd69bdfe0ca/routes/cards.js#L5
Роут ожидает `name` и `link` в параметрах запроса (`body`):
https://github.com/MaximMaslovVik/15_sprint/blob/39b375ef04ef4bde4276597bcc4dcbd69bdfe0ca/controllers/cards.js#L16
Оба этих поля нужно валидировать согласно схеме модели:
https://github.com/MaximMaslovVik/15_sprint/blob/39b375ef04ef4bde4276597bcc4dcbd69bdfe0ca/models/card.js#L6-L16

2. Роут `DELETE /cards/:cardId`:
https://github.com/MaximMaslovVik/15_sprint/blob/39b375ef04ef4bde4276597bcc4dcbd69bdfe0ca/routes/cards.js#L6
Роут ожидает `cardId` в параметрах запроса (`params`). Нужно проводить валидацию аналогичную роуту `GET /users/:userId`.

2020-02-04 16:56 UTC, aarefiev requested changes
Хорошо. К сожалению проверить работу сервера все еще не удается, по адресам указанным в README сервер не отвечает.
![image](https://user-images.githubusercontent.com/2168159/73766281-3e56e900-478f-11ea-8341-e50b1d8526c8.png)
![image](https://user-images.githubusercontent.com/2168159/73766317-49aa1480-478f-11ea-89ab-1b3d509a045a.png)

В режиме разработки сервер тоже все еще не удается запустить, при попытке запуска сервер падает с ошибкой. Об этом я указал ниже в списке ошибок.

**Нужно исправить:**
1. По ссылкам, указанным в README.md не удалось зайти на сервер по IP и доменному имени.
2. Ошибки линтинга.
3. Сервер не запускается.
4. Валидация поля `avatar` не соответствует схеме модели.
5. При получении списка карточек возвращается 404 без обработки ошибки централизованным обработчиком.
6. При возникновении ошибки на сервере при получении списка карточек возвращается 500 без обработки ошибки централизованным обработчиком.
7. В контроллере осталась валидация данных.
8. При ошибки на сервере возвращается 500 без обработки ошибки централизованным обработчиком.
9. При получении списка пользователей возвращается 404 без обработки ошибки централизованным обработчиком.
10. При возникновении ошибки на сервере при получении списка пользователей возвращается 500 без обработки ошибки централизованным обработчиком.
11. При ошибки во время регистрации пользователя возвращается 500 без обработки ошибки централизованным обработчиком.
12. При попытке зарегистрироваться с паролем менее 10 символов возвращается 500.
13. При попытке получить данные несуществующего пользователя возвращается 500 без обработки ошибки централизованным обработчиком.
14. При неудачной попытке авторизоваться возвращается 401 без обработки ошибки централизованным обработчиком.
15. Валидация поля `link` не соответствует схеме модели.
16. Некорректная схема вадиации роута `POST /cards`.

**Можно лучше:**
1. Добавить оформление в README.md.
2. Использовать метод .equals() при сравнении.
3. Убрать неиспользуемые файлы и код, который больше не используется.
4. Использовать готовые решения для валидации `id`.

---

**Развернутый комментарий к ошибке "Ошибки линтинга":**

При попытке запустить команду линтинга `npx eslint --ext .js .` линтер сообщает об ошибках:
```bash
$ npx eslint --ext .js .
...
✖ 4 problems (4 errors, 0 warnings)
  1 error and 0 warnings potentially fixable with the `--fix` option.
```
_часть вывода я намеренно опустил для экономии места_

Ожидаемый результат - ошибок маркерованных **error** нет (**warning** допускается).

2020-02-04 16:56 UTC, aarefiev commented on routes/cards.js
> +    cardId: Joi.string().alphanum().length(24),
Можно лучше: использовать готовые решения для валидации `id`.
Для того, чтобы корректно провести валидацию поля `id` для библиотеки `MongoDB` существует модуль [`joi-objectid`](https://www.npmjs.com/package/joi-objectid).

2020-02-04 16:56 UTC, aarefiev commented on routes/users.js
> +    userId: Joi.string().alphanum().length(24),
Можно лучше: использовать готовые решения для валидации `id`.
Для того, чтобы корректно провести валидацию поля `id` для библиотеки `MongoDB` существует модуль [`joi-objectid`](https://www.npmjs.com/package/joi-objectid).

2020-02-04 16:56 UTC, aarefiev commented on routes/cards.js
> +    createdAt: Joi.string().required(),
Нужно исправить: некорректная схема вадиации роута `POST /cards`.
При создании карточки контроллер ожидает только `name` и `link`, а `owner` использует из `req`:
https://github.com/MaximMaslovVik/15_sprint/blob/5d5e9a2f50c14679a7121290a01a3d3631ea96cc/controllers/cards.js#L20-L22
Нужно убрать `owner`, `likes` и `createdAt` отсюда.

2020-02-04 16:56 UTC, aarefiev commented on middlewares/errors/error_401.js
> +class Error401 extends Error {
Можно лучше: удалить неиспользуемые файлы.
Файл не импортируется ни в одном файле в репозитории.

2020-02-04 16:56 UTC, aarefiev commented on middlewares/errors/error_403.js
> +class Error403 extends Error {
Можно лучше: удалить неиспользуемые файлы.
Файл не импортируется ни в одном файле в репозитории.

2020-02-04 16:56 UTC, aarefiev commented on middlewares/errors/error_404.js
> +class Error404 extends Error {
Можно лучше: удалить неиспользуемые файлы.
Файл не импортируется ни в одном файле в репозитории.

2020-02-04 16:56 UTC, aarefiev commented on middlewares/errors/error_500.js
> +class Error500 extends Error {
Можно лучше: удалить неиспользуемые файлы.
Файл не импортируется ни в одном файле в репозитории.

2020-02-04 16:56 UTC, aarefiev commented on controllers/cards.js
> +        if (card.owner.toString() === req.user._id) {
Можно лучше: использовать метод `.equals()` при сравнении.
Экземпляр `card.owner` является экземпляром класса `Document`, у него есть метод [`.equals()`](https://mongoosejs.com/docs/api.html#document_Document-equals), который позволяет сравнивать данные. Это нужно затем, чтобы разработчики приложений не смотрели на типы.

Те так:
```suggestion
        if (card.owner.equals(req.user._id)) {
```

2020-02-04 16:56 UTC, aarefiev commented on controllers/cards.js
> +    .catch(() => res.status(500).send({ message: 'На сервере произошла ошибка' }));
Нужно исправить: при ошибки на сервере возвращается 500 без обработки ошибки централизованным обработчиком.
Здесь нужно точно также использовать `.catch()` вместе с `next` с передачей ошибки:
```suggestion
    .catch(() => next(new InternalServerError('На сервере произошла ошибка')));
```

Только ошибки `InternalServerError` нет, её нужно создать.

2020-02-04 16:56 UTC, aarefiev commented on controllers/users.js
>    if (password.length > 11) {
Можно лучше: убрать условие, оно больше не нужно.
Валидация данных переносится в роуты, где для этого роута есть проверка на минимальное количество символов:
https://github.com/MaximMaslovVik/15_sprint/blob/5d5e9a2f50c14679a7121290a01a3d3631ea96cc/app.js#L38

2020-02-04 16:56 UTC, aarefiev commented on controllers/users.js
> +    throw new Error500({ message: 'Слишком короткий пароль!' });
Нужно исправить: при попытке зарегистрироваться с паролем менее 10 символов возвращается 500.
Убираем, этого здесь делать не нужно, потому что валидация данных уходит в роуты.

2020-02-04 16:56 UTC, aarefiev commented on controllers/users.js
> +      .catch(() => res.status(500).send({ message: 'Не удалось создать пользователя' }));
Нужно исправить: при ошибки во время регистрации пользователя возвращается 500 без обработки ошибки централизованным обработчиком.
Здесь нужно точно также использовать `.catch()` вместе с `next` с передачей ошибки:
```suggestion
      .catch(() => next(new InternalServerError('Не удалось создать пользователя')));
```

Только ошибки `InternalServerError` нет, её нужно создать.

2020-02-04 16:56 UTC, aarefiev commented on controllers/users.js
> +        throw new NotFoundError({ message: 'Такого пользователя нет' });
Нужно исправить: при попытке получить данные несуществующего пользователя возвращается 500 без обработки ошибки централизованным обработчиком.
Это происходит из-за того, отправляется не то исключение, которое бросается.
https://github.com/MaximMaslovVik/15_sprint/blob/5d5e9a2f50c14679a7121290a01a3d3631ea96cc/controllers/users.js#L50
Нужно в блоке `.catch()` переделать обработку централизованному обработчику:
```js
.catch(next)
```

_не забываем про `next`, её нужно объявить_

2020-02-04 16:56 UTC, aarefiev commented on controllers/users.js
>  module.exports.getAllUsers = (req, res) => {
Нужно исправить: при получении списка пользователей возвращается 404 без обработки ошибки централизованным обработчиком.
Нужно также использовать `next`.

2020-02-04 16:56 UTC, aarefiev commented on controllers/users.js
>  module.exports.getAllUsers = (req, res) => {
Нужно исправить: при возникновении ошибки на сервере при получении списка пользователей возвращается 500 без обработки ошибки централизованным обработчиком.
Нужно также использовать `next`.

2020-02-04 16:56 UTC, aarefiev commented on controllers/users.js
>    const { email, password } = req.body;
Нужно исправить: при неудачной попытке авторизоваться возвращается 401 без обработки ошибки централизованным обработчиком.
https://github.com/MaximMaslovVik/15_sprint/blob/5d5e9a2f50c14679a7121290a01a3d3631ea96cc/controllers/users.js#L67-L69
Нужно также использовать `next`.

2020-02-04 16:56 UTC, aarefiev commented on controllers/cards.js
>      .catch(() => res.status(500).send({ message: 'Не удается создать карточку' }));
Нужно исправить: при возникновении ошибки на сервере при получении списка карточек возвращается 500 без обработки ошибки централизованным обработчиком.
Нужно также использовать `next`.

2020-02-04 16:56 UTC, aarefiev commented on controllers/cards.js
> +        throw new NotFoundError('База данных карточек пуста!');
Нужно исправить: при получении списка карточек возвращается 404 без обработки ошибки централизованным обработчиком.
Нужно также использовать `next`.

2020-02-04 16:56 UTC, aarefiev commented on controllers/cards.js
> +  }
Нужно исправить: в контроллере осталась валидация данных.
Валидация была перенесена в роуты. Это нужно сделать во всех контроллерах без исключения.

2020-02-04 16:56 UTC, aarefiev commented on app.js
> +    avatar: Joi.string().required(),
:exclamation: **ошибка с предыдущего ревью** ❗️ 

Нужно исправить: валидация поля `avatar` не соответствует схеме модели.
Ссылка на комментарий: https://github.com/MaximMaslovVik/15_sprint/pull/1/files#r373824065 .

2020-02-04 16:56 UTC, aarefiev commented on routes/cards.js
> +    link: Joi.string().required(),
Нужно исправить: валидация поля `link` не соответствует схеме модели.
В модели `Card` поле `link` проверяется на соответствие выражению:
https://github.com/MaximMaslovVik/15_sprint/blob/5d5e9a2f50c14679a7121290a01a3d3631ea96cc/models/card.js#L3
https://github.com/MaximMaslovVik/15_sprint/blob/5d5e9a2f50c14679a7121290a01a3d3631ea96cc/models/card.js#L14

2020-02-04 16:56 UTC, aarefiev commented on middlewares/logger.js
> +const expressWinston = require('express-winston');
Нужно исправить: сервер не запускается.
При попытке запустить сервер локально сервер падает и в консоли ошибка:
```bash
Error: Cannot find module 'winston'
Require stack:
- ~/15_sprint/middlewares/logger.js
- ~/15_sprint/app.js
```
Ошибка означает, что не удается найти модуль  `winston` и `express-winston`. Нужно установить их.

2020-02-19 17:12 UTC, aarefiev requested changes
Стало намного лучше. Сервер начал запускаться в режиме разработки. Но не удается пройти дальше регистрации. Также есть проблемы и к обращении к другим роутам. **Большая часть критических ошибок с прошлого ревью так и не была исправлена.** Повторяю их. 

Но большая беда с сервером в продакшене, обновленные адреса в README.md опять не работают

![image](https://user-images.githubusercontent.com/2168159/74856332-65024b80-535b-11ea-8ddb-817d2b19f9e0.png)
![image](https://user-images.githubusercontent.com/2168159/74856377-79464880-535b-11ea-85f3-0723d420fb64.png)

**Нужно исправить:**

1. По ссылкам, указанным в README.md не удалось зайти на сервер по IP и доменному имени.
2. Ошибки линтинга.
```
npx eslint --ext .js .

/Users/jmi/work/ya-reviews/15_sprint/controllers/cards.js
  28:46  error  Expected to return a value at the end of arrow function  consistent-return

✖ 1 problem (1 error, 0 warnings)
```
3. При попытке регистрации возникает ошибка.
4. Валидация поля `avatar` не соответствует схеме модели.
5. При возникновении ошибки на сервере при получении списка карточек возвращается 500 без обработки ошибки централизованным обработчиком.
6. В контроллере осталась валидация данных.
7. При получении списка пользователей возвращается 404 без обработки ошибки централизованным обработчиком.
8. При возникновении ошибки на сервере при получении списка пользователей возвращается 500 без обработки ошибки централизованным обработчиком.
9. При попытке зарегистрироваться с паролем менее 10 символов возвращается 500.
10. При попытке получить данные несуществующего пользователя возвращается 500 без обработки ошибки централизованным обработчиком.
11. При неудачной попытке авторизоваться возвращается 401 без обработки ошибки централизованным обработчиком.
12. При обращении на роут закрытый авторизацией в консоли ошибка.
13. Валидация поля `link` не соответствует схеме модели.
14. Некорректная схема вадиации роута `POST /cards`.

По улучшениям рекомендую посмотреть прошлое ревью.

2020-02-19 17:12 UTC, aarefiev commented on middlewares/auth.js
> +
Нужно исправить: при обращении на роут закрытый авторизацией в консоли ошибка.
```bash
Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at ServerResponse.setHeader (_http_outgoing.js:523:11)
```

Это происходит из-за того, что в мидлваре сначала отправляется 401 и сообщение об ошибке авторизации:
https://github.com/MaximMaslovVik/15_sprint/blob/5f262f84d095f547691f3ab2599f8df612dfa552/middlewares/auth.js#L20-L22
или при ошибке проверки токена:
https://github.com/MaximMaslovVik/15_sprint/blob/5f262f84d095f547691f3ab2599f8df612dfa552/middlewares/auth.js#L29-L31
а затем передается управление следующей мидлваре:
https://github.com/MaximMaslovVik/15_sprint/blob/5f262f84d095f547691f3ab2599f8df612dfa552/middlewares/auth.js#L33

Основная концепция, которую следует понять в этой практике - это использование централизованного обработчика ошибок. Вот он:
https://github.com/MaximMaslovVik/15_sprint/blob/5f262f84d095f547691f3ab2599f8df612dfa552/app.js#L68-L71
Использование достигается за счет передачи ошибки из источника, где ошибка возникла в централизованный обработчик ошибок, путем передачи ошибки при вызове `next()`:
```js
// подключаем ошибку 401
const Error401 = require('../errors/error_401');

module.exports = (req, res, next) => {
  const cookie = req.cookies.jwt;

  if (!cookie) {
    // `jwt` нет передаем ошибку в централизованный обработчик ошибок
    // и завершаем выполнение функции
    return next(new Error401('Доступ запрещен. Необходима авторизация'));
  }

  let payload;

  try {
    payload = jwt.verify(cookie, JWT_SECRET);
    req.user = payload;
  } catch (err) {
    // ошибка при валидации `jwt` - передаем ошибку в централизованный обработчик ошибок
    // и завершаем выполнение функции
    return next(new Error401('Доступ запрещен. Необходима авторизация'));
  }

  next();
};
```

2020-02-19 17:12 UTC, aarefiev commented on app.js
> +    avatar: Joi.string().required(),
❗️ **ошибка с предыдущего ревью** ❗️

Нужно исправить: валидация поля avatar не соответствует схеме модели.
Ссылка на комментарий: https://github.com/MaximMaslovVik/15_sprint/pull/1/files#r373824065 .

2020-02-19 17:12 UTC, aarefiev commented on app.js
> +app.post('/signup', celebrate({
Нужно исправить: при попытке регистрации возникает ошибка.
Ошибка возникает потому что мидлвары, которые работают с `body` и с `cookies` должны быть подключены до роута:
https://github.com/MaximMaslovVik/15_sprint/blob/5f262f84d095f547691f3ab2599f8df612dfa552/app.js#L52-L54

Общее правило - первым делом подключаем все мидлвары обрабатывающие запросы, после них роуты, а уже после роутов .- централизованный обработчик несуществующего роута и обработчик ошибок. Эту иерархию стоит представить в виде множества пропускных пунктов, чтобы следующий работал верно, нужно чтобы предыдущий сделал свою работу.

Следующее также нужно выносить вниз:
https://github.com/MaximMaslovVik/15_sprint/blob/5f262f84d095f547691f3ab2599f8df612dfa552/app.js#L28-L32
и
https://github.com/MaximMaslovVik/15_sprint/blob/5f262f84d095f547691f3ab2599f8df612dfa552/app.js#L45-L50

2020-02-19 17:12 UTC, aarefiev commented on controllers/users.js
> +    throw new Error500({ message: 'Слишком короткий пароль!' });
❗️ **ошибка с предыдущего ревью** ❗️

Нужно исправить: при попытке зарегистрироваться с паролем менее 10 символов возвращается 500.
Ссылка на комментарий: https://github.com/MaximMaslovVik/15_sprint/pull/1/files#r374775887 .

2020-02-19 17:12 UTC, aarefiev commented on controllers/users.js
> +    .catch((new Error500('Нет пользователя с таким id')));
Нужно исправить: при попытке получить данные несуществующего пользователя возвращается 500 без обработки ошибки централизованным обработчиком.
Нужно передавать обработку централизованному обработчику через `next`.

2020-02-19 17:12 UTC, aarefiev commented on controllers/users.js
>    const { email, password } = req.body;
❗️ **ошибка с предыдущего ревью** ❗️
Нужно исправить: при неудачной попытке авторизоваться возвращается 401 без обработки ошибки централизованным обработчиком.
Ссылка на комментарий: https://github.com/MaximMaslovVik/15_sprint/pull/1/files#r374782715 .

2020-02-19 17:12 UTC, aarefiev commented on routes/cards.js
> +    link: Joi.string().required(),
❗️ **ошибка с предыдущего ревью** ❗️
Нужно исправить: валидация поля `link` не соответствует схеме модели.
Ссылка на комментарий: https://github.com/MaximMaslovVik/15_sprint/pull/1/files#r374789093 .

2020-02-19 17:12 UTC, aarefiev commented on routes/cards.js
> +    createdAt: Joi.string().required(),
❗️ **ошибка с предыдущего ревью** ❗️
Нужно исправить: некорректная схема вадиации роута `POST /cards.`.
Ссылка на комментарий: https://github.com/MaximMaslovVik/15_sprint/pull/1/files#r374761987 .

2020-02-19 17:12 UTC, aarefiev commented on controllers/cards.js
>      .catch(() => res.status(500).send({ message: 'Не удается создать карточку' }));
❗️ **ошибка с предыдущего ревью** ❗️
Нужно исправить: при возникновении ошибки на сервере при получении списка карточек возвращается 500 без обработки ошибки централизованным обработчиком.
Ссылка на комментарий: https://github.com/MaximMaslovVik/15_sprint/pull/1/files#r374784019 .

2020-02-19 17:12 UTC, aarefiev commented on controllers/cards.js
> +  }
❗️**ошибка с предыдущего ревью**❗️
Нужно исправить: в контроллере осталась валидация данных.
Ссылка на комментарий: https://github.com/MaximMaslovVik/15_sprint/pull/1/files#r374784806 .

2020-02-19 17:12 UTC, aarefiev commented on controllers/users.js
>  module.exports.getAllUsers = (req, res) => {
❗️**ошибка с предыдущего ревью**❗️
Нужно исправить: при получении списка пользователей возвращается 404 без обработки ошибки централизованным обработчиком.
Ссылка на комментарий: https://github.com/MaximMaslovVik/15_sprint/pull/1/files#r374780170 .

2020-02-19 17:12 UTC, aarefiev commented on controllers/users.js
>  module.exports.getAllUsers = (req, res) => {
❗️**ошибка с предыдущего ревью**❗️
Нужно исправить: при возникновении ошибки на сервере при получении списка пользователей возвращается 500 без обработки ошибки централизованным обработчиком.
Ссылка на комментарий: https://github.com/MaximMaslovVik/15_sprint/pull/1/files#r374780369 .

2020-02-22 18:52 UTC, aarefiev requested changes
Сервер из описания заработал. Но дальше регистрации и авторизации не удалось пройти.
Нужно исправить ошибки.

**Нужно исправить:**
1. Ошибки линтинга:
```bash
$ npx eslint --ext .js . 

~/15_sprint/controllers/cards.js
  21:9   error  'owner' is assigned a value but never used               no-unused-vars
  28:46  error  Expected to return a value at the end of arrow function  consistent-return

~/15_sprint/middlewares/auth.js
  12:35  error  Expected to return a value at the end of arrow function  consistent-return

✖ 3 problems (3 errors, 0 warnings)
```
2.  При попытке регистрации возникает ошибка.
3.  При попытке авторизации сервер зависает и ошибки в консоли.

2020-02-22 18:52 UTC, aarefiev commented on app.js
> +app.post('/signup', celebrate({
Нужно исправить: при попытке регистрации возникает ошибка.
```
{
    "message": "Cannot destructure property 'name' of 'req.body' as it is undefined."
}
```
Ошибка возникает потому что мидлвары, которые работают с `body` и с `cookies` должны быть подключены до роута:
https://github.com/MaximMaslovVik/15_sprint/blob/36715f87a28e1f0008ec9bc72f321d6a96155b34/app.js#L38-L40

Общее правило - первым делом подключаем все мидлвары обрабатывающие запросы, после них роуты, а уже после роутов .- централизованный обработчик несуществующего роута и обработчик ошибок. Эту иерархию стоит представить в виде множества пропускных пунктов, чтобы следующий работал верно, нужно чтобы предыдущий сделал свою работу.

2020-02-22 18:52 UTC, aarefiev commented on app.js
> +app.post('/signup', celebrate({
Нужно исправить: при попытке авторизации сервер зависает и ошибки в консоли.
```bash
(node:33176) UnhandledPromiseRejectionWarning: Error: Неправильные почта или пароль
    at ~/15_sprint/models/user.js:43:31
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:33176) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:33176) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
При ошибке авторизации нужно возвращать 401, а ошибок в консоли не должно быть.

2020-02-22 18:52 UTC, aarefiev commented on app.js
> +    avatar: Joi.string().required(),
❗️ ошибка с предыдущего ревью ❗️
Нужно исправить: валидация поля `avatar` не соответствует схеме модели.
Ссылка на комментарий: https://github.com/MaximMaslovVik/15_sprint/pull/1/files#r373824065 .

2020-02-28 17:05 UTC, aarefiev requested changes
Стало лучше. Но есть большие ошибки в обработке, чтобы проверять детально нужно исправлять код. Я постарался детально расписать в чем ошибка и что нужно исправить.

**Нужно исправить:**
1. Cхема роута `POST /signup` не соответствует схеме модели.
2. Нет валидации роута `POST /signin`.
3. Обработка роутов `celebrate` не срабатывает.
4. Возникает ошибка в консоли при получении списка карточек.
5. Ошибка не обрабатывается централизованным обработчиком.
6. Поле `avatar` должно быть формата `URL`.
7. Схема роута `POST /cards` не соответствует схеме модели.

2020-02-28 17:05 UTC, aarefiev commented on app.js
> +app.use(errors());
Нужно исправить: обработка роутов `celebrate` не срабатывает.
Это происходит из-за того, что [централизованный обработчик ошибок](https://github.com/MaximMaslovVik/15_sprint/blob/9aae875d58b5031fbc6c13ac1f5332065778c271/app.js#L62-L65) назначен **ранее** чем срабатывает [обработчик `celebrate`](https://github.com/MaximMaslovVik/15_sprint/blob/9aae875d58b5031fbc6c13ac1f5332065778c271/app.js#L68).

Чтобы это исправить, нужно централизованный обработчик опустить вниз:
 ```suggestion
app.use(errorLogger);
app.use(errors());
app.use((err, req, res, next) => {
  res.status(err.statusCode || 500).send({ message: err.message });
  next();
});
```

2020-02-28 17:05 UTC, aarefiev commented on app.js
> +  }),
Нужно исправить: схема роута `POST /signup` не соответствует схеме модели.
Схема роута должна проверять те же самые поля, которые используются при создании записи в базе данных. Модель ожидает, что будет передано:
https://github.com/MaximMaslovVik/15_sprint/blob/9aae875d58b5031fbc6c13ac1f5332065778c271/controllers/users.js#L25-L27

Нужно добавить поле `avatar` в схему роута. Так как `avatar` должен быть вида `url` то я рекомендую воспользоваться соответстующей валидацией: [`uri()`](https://github.com/hapijs/joi/blob/master/API.md#stringurioptions).

2020-02-28 17:05 UTC, aarefiev commented on app.js
>  app.post('/signin', login);
Нужно исправить: нет валидации роута `POST /signin`.
Схема роута должна проверять те же самые поля, которые используются при создании записи в базе данных. Модель ожидает, что будет передано:
https://github.com/MaximMaslovVik/15_sprint/blob/9aae875d58b5031fbc6c13ac1f5332065778c271/controllers/users.js#L51

Важно задать для этих полей такую же схему, как и схема этих же полей в роуте `POST /signup`:
https://github.com/MaximMaslovVik/15_sprint/blob/9aae875d58b5031fbc6c13ac1f5332065778c271/app.js#L34-L35

2020-02-28 17:05 UTC, aarefiev commented on controllers/cards.js
>      })
Нужно исправить: возникает ошибка в консоли при получении списка карточек.
Это потому что здесь бросается исключение, которое не обрабатывается. Но я рекомендую здесь лучше убрать эту ошибку. Сделаем, чтобы если карточек нет, будет возвращаться пустой массив карточек. Это в целом по заданию ок:
```js
.then((card) => res.send({ data: card })
```

2020-02-28 17:05 UTC, aarefiev commented on controllers/cards.js
> +    .catch(new Error500('Ошибка сервера'));
Нужно исправить: ошибка не обрабатывается централизованным обработчиком.
Централизованная обработка ошибок запустится только если будет вызван `next`:
```suggestion
    .catch(next);
```

Только нужно не забыть объявить `next` здесь:
https://github.com/MaximMaslovVik/15_sprint/blob/9aae875d58b5031fbc6c13ac1f5332065778c271/controllers/users.js#L13

2020-02-28 17:05 UTC, aarefiev commented on routes/cards.js
> +}), createCard);
Нужно исправить: схема роута `POST /cards` не соответствует схеме модели.
Схема роута должна проверять те же самые поля, которые используются при создании записи в базе данных. Модель ожидает, что будет передано:
https://github.com/MaximMaslovVik/15_sprint/blob/9aae875d58b5031fbc6c13ac1f5332065778c271/controllers/cards.js#L22
Схему для каждого параметра нужно смотреть здесь:
https://github.com/MaximMaslovVik/15_sprint/blob/9aae875d58b5031fbc6c13ac1f5332065778c271/models/card.js

Нужно убрать лишние поля. Так как `link` должен быть вида `url` то я рекомендую воспользоваться соответстующей валидацией: [`uri()`](https://github.com/hapijs/joi/blob/master/API.md#stringurioptions).

2020-02-28 17:05 UTC, aarefiev commented on models/user.js
>      required: true,
Нужно исправить: поле `avatar` должно быть формата `URL`.
Нужно вернуть `match: validate` и регулярку.

2020-02-29 17:29 UTC, aarefiev requested changes
Стало лучше, роуты начали работать. Но пока ошибок очень много, нужно разобраться со схемой роутов и чтобы контроллеры передавали обработку ошибок в централизованный обработчик. Чтобы не засорять контекст, я выделил основные. После их решения поправить оставшиеся будет просто.

На текущей проверке основаная проблема - это, то что сервер не запускался вовсе:
![image](https://user-images.githubusercontent.com/2168159/75612128-28440a80-5b3a-11ea-8841-d0a4fb07f9eb.png)

**Убедительно прошу проверять работу перед тем как сдать на ревью.** Я ожидаю, сервер запускается и что все ошибки которые описаны в секции **Нужно исправить** будут исправлены.

**Нужно исправить:**
1. Сервер не запускается, ошибки в консоли.
2. Возникает ошибка в консоли при получении списка карточек.
3. Ошибка не обрабатывается централизованным обработчиком.
4. Поле `avatar` должно быть формата `URL`.
5. Схема роута `POST /cards` не соответствует схеме модели.

2020-02-29 17:29 UTC, aarefiev commented on app.js
> +});
Нужно исправить: сервер не запускается, ошибки в консоли.
Ошибка:
```bash
/Users/jmi/work/ya-reviews/15_sprint/app.js:21
  ];
   ^

SyntaxError: Unexpected token ';'
    at wrapSafe (internal/modules/cjs/loader.js:1050:16)
    at Module._compile (internal/modules/cjs/loader.js:1098:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
    at Module.load (internal/modules/cjs/loader.js:983:32)
    at Function.Module._load (internal/modules/cjs/loader.js:891:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
[nodemon] app crashed - waiting for file changes before starting...
```
Если этот код не используется, то его лучше полностью удалить.

2020-02-29 17:29 UTC, aarefiev commented on controllers/cards.js
>      })
Нужно исправить: возникает ошибка в консоли при получении списка карточек.
Ошибка:
```bash
(node:60549) UnhandledPromiseRejectionWarning: Error: База данных карточек пуста!
    at /Users/jmi/work/ya-reviews/15_sprint/controllers/cards.js:13:15
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:60549) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 5)
(node:60549) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
Это потому что здесь бросается исключение, которое не обрабатывается. Но я рекомендую здесь лучше убрать эту ошибку. Сделаем, чтобы если карточек нет, будет возвращаться пустой массив карточек. Это в целом по заданию ок:
```js
.then((card) => res.send({ data: card })
```

2020-02-29 17:29 UTC, aarefiev commented on controllers/cards.js
> +    .catch(new Error500('Ошибка сервера'));
Нужно исправить: ошибка не обрабатывается централизованным обработчиком.
Централизованная обработка ошибок запустится только если будет вызван `next`:
```suggestion
    .catch(next);
```

Только нужно не забыть объявить `next` здесь:
https://github.com/MaximMaslovVik/15_sprint/blob/9aae875d58b5031fbc6c13ac1f5332065778c271/controllers/users.js#L13

2020-02-29 17:29 UTC, aarefiev commented on controllers/cards.js
> +    .catch(new Error500({ message: 'Не удается создать карточку' }));
Нужно исправить: ошибка не обрабатывается централизованным обработчиком.
Централизованная обработка ошибок запустится только если будет вызван `next`:
```suggestion
    .catch(next);
```

Только нужно не забыть объявить `next` здесь:
https://github.com/MaximMaslovVik/15_sprint/blob/2ad864e57b00f8564f3658374d392b861c3b10fb/controllers/cards.js#L20

2020-02-29 17:29 UTC, aarefiev commented on controllers/users.js
> +    .catch((new Error500('На сервере произошла ошибка')));
Нужно исправить: ошибка не обрабатывается централизованным обработчиком.
Централизованная обработка ошибок запустится только если будет вызван `next`:
```suggestion
    .catch(next);
```

Только нужно не забыть объявить `next` здесь:
https://github.com/MaximMaslovVik/15_sprint/blob/2ad864e57b00f8564f3658374d392b861c3b10fb/controllers/users.js#L13

2020-02-29 17:29 UTC, aarefiev commented on controllers/users.js
> +      .catch(new Error500('Не удалось создать пользователя'));
Нужно исправить: ошибка не обрабатывается централизованным обработчиком.
Централизованная обработка ошибок запустится только если будет вызван `next`:
```suggestion
      .catch(next);
```

Только нужно не забыть объявить `next` здесь:
https://github.com/MaximMaslovVik/15_sprint/blob/2ad864e57b00f8564f3658374d392b861c3b10fb/controllers/users.js#L24

2020-02-29 17:29 UTC, aarefiev commented on controllers/users.js
> +    .catch(new Error500('Нет пользователя с таким id'));
Нужно исправить: ошибка не обрабатывается централизованным обработчиком.
Централизованная обработка ошибок запустится только если будет вызван `next`:
```suggestion
    .catch(next);
```

Только нужно не забыть объявить `next` здесь:
https://github.com/MaximMaslovVik/15_sprint/blob/2ad864e57b00f8564f3658374d392b861c3b10fb/controllers/users.js#L38

2020-02-29 17:29 UTC, aarefiev commented on controllers/users.js
> +    .catch(new Error401('Ошибка ввода'));
Нужно исправить: ошибка не обрабатывается централизованным обработчиком.
Централизованная обработка ошибок запустится только если будет вызван `next`:
```suggestion
    .catch(next);
```

Только нужно не забыть объявить `next` здесь:
https://github.com/MaximMaslovVik/15_sprint/blob/2ad864e57b00f8564f3658374d392b861c3b10fb/controllers/users.js#L50

2020-02-29 17:29 UTC, aarefiev commented on models/user.js
>      required: true,
Нужно исправить: поле `avatar` должно быть формата `URL`.
Нужно вернуть `match: validate` и регулярку.

2020-02-29 17:29 UTC, aarefiev commented on routes/cards.js
> +}), createCard);
Нужно исправить: схема роута `POST /cards` не соответствует схеме модели.
Схема роута должна проверять те же самые поля, которые используются при создании записи в базе данных. Модель ожидает, что будет передано:
https://github.com/MaximMaslovVik/15_sprint/blob/9aae875d58b5031fbc6c13ac1f5332065778c271/controllers/cards.js#L22
Схему для каждого параметра нужно смотреть здесь:
https://github.com/MaximMaslovVik/15_sprint/blob/9aae875d58b5031fbc6c13ac1f5332065778c271/models/card.js

Нужно убрать лишние поля. Так как `link` должен быть вида `url` то я рекомендую воспользоваться соответстующей валидацией: [`uri()`](https://github.com/hapijs/joi/blob/master/API.md#stringurioptions).

2020-03-03 19:05 UTC, aarefiev requested changes
В работе в целом хаос, я беспокоюсь, что не в состоянии донести информацию через ревью. В работе есть одна основная проблема:
- нет представления о том как работают мидлвары в `express`, что такое `next` и как его использовать для передачи ошибок в централизованный обработчик

Рекомендую почитать статьи чтобы разобраться с этим подробнее:
- [Написание кода промежуточных обработчиков для использования в приложениях Express ](https://expressjs.com/ru/guide/writing-middleware.html),
- [Использование промежуточных обработчиков](https://expressjs.com/ru/guide/using-middleware.html),
- [Обработка ошибок](https://expressjs.com/ru/guide/error-handling.html)

Ревью буду делать итеративно. Чтобы проще было добраться до нужного результата. Когда я присылаю все ошибки, которые есть, то большая часть из них игнорируется. Первым делом нужно исправить обработку ошибок.

**Нужно исправить:**
1. [Возникает ошибка в консоли при получении списка карточек.](https://github.com/MaximMaslovVik/15_sprint/pull/1#discussion_r386041680)
2. Ошибка не обрабатывается централизованным обработчиком:
- https://github.com/MaximMaslovVik/15_sprint/pull/1#discussion_r386041754,
- https://github.com/MaximMaslovVik/15_sprint/pull/1#discussion_r386041787,
- https://github.com/MaximMaslovVik/15_sprint/pull/1#discussion_r386041893,
- https://github.com/MaximMaslovVik/15_sprint/pull/1#discussion_r386041921,
- https://github.com/MaximMaslovVik/15_sprint/pull/1#discussion_r386041982,
- https://github.com/MaximMaslovVik/15_sprint/pull/1#discussion_r386042114

2020-03-03 20:11 UTC, MaximMaslovVik commented
> В работе в целом хаос, я беспокоюсь, что не в состоянии донести информацию через ревью. В работе есть одна основная проблема:
> 
> * нет представления о том как работают мидлвары в `express`, что такое `next` и как его использовать для передачи ошибок в централизованный обработчик
> 
> Рекомендую почитать статьи чтобы разобраться с этим подробнее:
> 
> * [Написание кода промежуточных обработчиков для использования в приложениях Express ](https://expressjs.com/ru/guide/writing-middleware.html),
> * [Использование промежуточных обработчиков](https://expressjs.com/ru/guide/using-middleware.html),
> * [Обработка ошибок](https://expressjs.com/ru/guide/error-handling.html)
> 
> Ревью буду делать итеративно. Чтобы проще было добраться до нужного результата. Когда я присылаю все ошибки, которые есть, то большая часть из них игнорируется. Первым делом нужно исправить обработку ошибок.
> 
> **Нужно исправить:**
> 
> 1. [Возникает ошибка в консоли при получении списка карточек.](https://github.com/MaximMaslovVik/15_sprint/pull/1#discussion_r386041680)
> 2. Ошибка не обрабатывается централизованным обработчиком:
> 
> * [#1 (comment)](https://github.com/MaximMaslovVik/15_sprint/pull/1#discussion_r386041754),
> * [#1 (comment)](https://github.com/MaximMaslovVik/15_sprint/pull/1#discussion_r386041787),
> * [#1 (comment)](https://github.com/MaximMaslovVik/15_sprint/pull/1#discussion_r386041893),
> * [#1 (comment)](https://github.com/MaximMaslovVik/15_sprint/pull/1#discussion_r386041921),
> * [#1 (comment)](https://github.com/MaximMaslovVik/15_sprint/pull/1#discussion_r386041982),
> * [#1 (comment)](https://github.com/MaximMaslovVik/15_sprint/pull/1#discussion_r386042114)

исправил, не понимаю как мне ловить ошибки,? постмен не выдает ошибок, вьюкод тоже, и браузер и консоль, тыкаюсь как слепой

2020-03-04 04:21 UTC, aarefiev commented
> исправил, не понимаю как мне ловить ошибки,? постмен не выдает ошибок, вьюкод тоже, и браузер и консоль, тыкаюсь как слепой

@MaximMaslovVik сейчас расскажу. Нужно повторить процесс, который делаю я. Проверка всегда происходит на чистой базе данных. Поэтому первым делом нужно её подчистить (можно подключиться к `mongo` через консоль, либо использовать [Compas](https://www.mongodb.com/products/compass)). Далее нужно через Postman выполнять запросы на роуты.
Перед использованием, рекомендую подчистить куки в Postman. Доступ к ним располагается под кнопкой отправки:
![image](https://user-images.githubusercontent.com/2168159/75844278-f4453f80-5dee-11ea-8b2e-7c3d4d92f6ee.png)
Я тестирую так (предварительно удалив куки):
1. Проверка на работу мидлвары. Любой запрос на закрытый роут, например: `GET` на http://localhost:3000/users (должен быть получен 401 код).
2. Проверка регистрации (`POST` на http://localhost:3000/signup/):
- Проверяем валидацию роутинга:
  - Отправляем запрос с пустым `body` (должен быть получен 400 код),
  - Отправляем запрос с ошибками в параметрах, так чтобы значения не соответствовали схеме (должен быть получен 400 код),
- Проверяем сохранение пользователя:
  - Отправляем запрос с корректным `body` (должен быть получен 200 или 201 код),
2. Проверка авторизации (`POST` на http://localhost:3000/signin`). Повторяем все по аналогии с регистрацией.
3. Проверка получения пользователей (`GET` на http://localhost:3000/users/) (должен быть получен список пользователей и 200 код).
4. Проверка получения пользователя по `id`:
- Проверяем валидацию роутинга:
  - Отправляем запрос с некорректным `id` (должен быть получен 400 код),
- Проверяем получение пользователя:
  - Отправляем запрос с корректным `id`, но таким, чтобы в базе не было пользователя с таким `id` (должен быть получен 404 код),
  - Отправляем запрос с корректным `id` существующего пользователя (должен быть получен 200 код)
5. Проверка получения карточек (`GET` на http://localhost:3000/cards/) (я помню в 12-й практике просил кидать 404 ошибку, потому что там это было чисто в обучающих целей, здесь можно отправлять 200 код и пустой массив) (должен быть получен список карточек и 200 код).
6. Проверка создания карточки (`POST` на http://localhost:3000/cards/). Повторяем все по аналогии с регистрацией.
7. Проверка удаления карточки по `id`. Повторяем по аналогии с получением пользователя по `id`. Для проверки прав удаления карточки нужно создать карточку под одним пользователем, произвести новую регистрацию и авторизацию и попытаться эту карту удалить (должен быть получен 403 код).
8. Проверка несуществующего роута. Любой запрос на несуществующий роут, например, `POST на http://localhost:3000/.

Вот если удастся проверить по этому списку работу перед сдачей, то можно будет выявить абсолютно все ошибки о которых я писал. Не всегда ошибка будет вернута в `Postman`, если ответ не приходит, то появится ошибка в консоли терминала где запущен сервер.
Надеюсь, помог 👷 .

2020-03-04 16:16 UTC, MaximMaslovVik commented
спасибо!!!
 проверил по вашему плану все есть, но мне кажется и еще где то ошибки. не могу их отловить

2020-03-04 16:25 UTC, aarefiev commented
> спасибо!!!
> проверил по вашему плану все есть, но мне кажется и еще где то ошибки. не могу их отловить

Максим, есть ошибки. Попробую детально расписать как их воспроизвел.

2020-03-04 17:02 UTC, aarefiev requested changes
Сейчас основная ошибка в `.catch(next(new Error401('Ошибка ввода')));`. В комментарии к регистрации я расписал в чем ошибка при такой записи. 
Напоминаю, действуем точно также как я написал в [комментарии](https://github.com/MaximMaslovVik/15_sprint/pull/1#issuecomment-594318643). При таком подходе удастся исправить эту ошибку.

**Нужно исправить:**
1. При получении списка пользователей возвращается 500 и ошибка в консоли.
2. При создании карточки возвращается 500 и ошибка в консоли.
3. Возвращается 404 при удалении карточки чужого пользователя.
4. При удалении карточки возвращается 500 и ошибка в консоли.
5. При получении списка пользователей возвращается 500 и ошибка в консоли.
6. При регистрации возвращается 500 и ошибка в консоли.
7. При получении пользователя по id возвращается 500 и ошибка в консоли.
8. При авторизации возвращается 401 и ошибка в консоли.

2020-03-04 17:02 UTC, aarefiev commented on controllers/users.js
> +      .catch(next(new Error500('Не удалось создать пользователя')));
Нужно исправить: при регистрации возвращается 500 и ошибка в консоли.
Как воспроизвести:
1. Почистить базу и куки.
2. Отправить `POST` запрос с корректными данными в `body` на `/signup`.
Что будет получено:
- в Postman:
```json
{
    "message": "Не удалось создать пользователя"
}
```
- в консоли терминала:
```bash
(node:69484) UnhandledPromiseRejectionWarning: MongoError: E11000 duplicate key error collection: mestodb.users index: email_1 dup key: { email: "username1@mail.ru" }
    at Function.create (/Users/jmi/work/ya-reviews/15_sprint/node_modules/mongodb/lib/core/error.js:44:12)
    at toError (/Users/jmi/work/ya-reviews/15_sprint/node_modules/mongodb/lib/utils.js:150:22)
    at /Users/jmi/work/ya-reviews/15_sprint/node_modules/mongodb/lib/operations/common_functions.js:265:39
    at handler (/Users/jmi/work/ya-reviews/15_sprint/node_modules/mongodb/lib/core/sdam/topology.js:971:24)
    at /Users/jmi/work/ya-reviews/15_sprint/node_modules/mongodb/lib/core/sdam/server.js:496:5
    at /Users/jmi/work/ya-reviews/15_sprint/node_modules/mongodb/lib/core/connection/pool.js:420:18
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
(node:69484) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
```
Здесь ошибка в том, что коротая запись передачи функции в стрелочную функцию записана неверно. Вместо передачи `next` передается результат вызова `next(new Error500('Не удалось создать пользователя')`. Нужно передавать только `next`:
```suggestion
      .catch(next);
```

2020-03-04 17:02 UTC, aarefiev commented on controllers/users.js
> +    .catch(next(new Error401('Ошибка ввода')));
Нужно исправить: при авторизации возвращается 401 и ошибка в консоли.
Общее поведение аналогично ошибке при регистрации. Чинится точно также.

Как воспроизвести:
1. Отправить `POST` запрос с корректными данными в `body` на `/signin`.
Что будет получено:
- в Postman:
```json
{
    "message": "Ошибка ввода"
}
```
- в консоли терминала:
```bash
(node:69484) UnhandledPromiseRejectionWarning: Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at ServerResponse.setHeader (_http_outgoing.js:523:11)
    at ServerResponse.header (/Users/jmi/work/ya-reviews/15_sprint/node_modules/express/lib/response.js:771:10)
    at ServerResponse.append (/Users/jmi/work/ya-reviews/15_sprint/node_modules/express/lib/response.js:732:15)
    at ServerResponse.res.cookie (/Users/jmi/work/ya-reviews/15_sprint/node_modules/express/lib/response.js:857:8)
    at /Users/jmi/work/ya-reviews/15_sprint/controllers/users.js:55:10
(node:69484) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
```

2020-03-04 17:02 UTC, aarefiev commented on controllers/users.js
> +    .catch(next(new Error500('На сервере произошла ошибка')));
Нужно исправить: при получении списка пользователей возвращается 500 и ошибка в консоли.
Общее поведение аналогично ошибке при регистрации. Чинится точно также.

Как воспроизвести:
1. Отправить `GET` запрос на `/users`.
Что будет получено:
- в Postman:
```json
{
    "message": "На сервере произошла ошибка"
}
```
- в консоли терминала:
```bash
(node:69538) UnhandledPromiseRejectionWarning: Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at ServerResponse.setHeader (_http_outgoing.js:523:11)
    at ServerResponse.header (/Users/jmi/work/ya-reviews/15_sprint/node_modules/express/lib/response.js:771:10)
    at ServerResponse.send (/Users/jmi/work/ya-reviews/15_sprint/node_modules/express/lib/response.js:170:12)
    at ServerResponse.json (/Users/jmi/work/ya-reviews/15_sprint/node_modules/express/lib/response.js:267:15)
    at ServerResponse.send (/Users/jmi/work/ya-reviews/15_sprint/node_modules/express/lib/response.js:158:21)
    at /Users/jmi/work/ya-reviews/15_sprint/controllers/users.js:19:18
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:69538) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:69538) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

2020-03-04 17:02 UTC, aarefiev commented on controllers/users.js
> +    .catch(next(new Error500('Нет пользователя с таким id')));
Нужно исправить: при получении пользователя по `id` возвращается 500 и ошибка в консоли.
Общее поведение аналогично ошибке при регистрации. Чинится точно также.

Как воспроизвести:
1. Отправить `GET` запрос на `/users/:id` (где `:id` - `id` какого-нибудь пользователя).
Что будет получено:
- в Postman:
```json
{
    "message": "Нет пользователя с таким id"
}
```
- в консоли терминала:
```bash
(node:69556) UnhandledPromiseRejectionWarning: Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at ServerResponse.setHeader (_http_outgoing.js:523:11)
    at ServerResponse.header (/Users/jmi/work/ya-reviews/15_sprint/node_modules/express/lib/response.js:771:10)
    at ServerResponse.send (/Users/jmi/work/ya-reviews/15_sprint/node_modules/express/lib/response.js:170:12)
    at ServerResponse.json (/Users/jmi/work/ya-reviews/15_sprint/node_modules/express/lib/response.js:267:15)
    at ServerResponse.send (/Users/jmi/work/ya-reviews/15_sprint/node_modules/express/lib/response.js:158:21)
    at /Users/jmi/work/ya-reviews/15_sprint/controllers/users.js:43:13
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:69556) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:69556) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

2020-03-04 17:02 UTC, aarefiev commented on controllers/cards.js
> +    .catch(next(new Error500('Ошибка сервера')));
Нужно исправить: при получении списка пользователей возвращается 500 и ошибка в консоли.
Общее поведение аналогично ошибке при регистрации. Чинится точно также.

Как воспроизвести:
1. Отправить `GET` запрос на `/cards`.
Что будет получено:
- в Postman:
```json
{
    "message": "Ошибка сервера"
}
```
- в консоли терминала:
```bash
(node:69556) UnhandledPromiseRejectionWarning: Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at ServerResponse.setHeader (_http_outgoing.js:523:11)
    at ServerResponse.header (/Users/jmi/work/ya-reviews/15_sprint/node_modules/express/lib/response.js:771:10)
    at ServerResponse.send (/Users/jmi/work/ya-reviews/15_sprint/node_modules/express/lib/response.js:170:12)
    at ServerResponse.json (/Users/jmi/work/ya-reviews/15_sprint/node_modules/express/lib/response.js:267:15)
    at ServerResponse.send (/Users/jmi/work/ya-reviews/15_sprint/node_modules/express/lib/response.js:158:21)
    at /Users/jmi/work/ya-reviews/15_sprint/controllers/cards.js:15:25
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:69556) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
```

2020-03-04 17:02 UTC, aarefiev commented on controllers/cards.js
> +    .catch(next(new Error500({ message: 'Не удается создать карточку' })));
Нужно исправить: при создании карточки возвращается 500 и ошибка в консоли.
Как воспроизвести:
1. Отправить `POST` запрос с заполненным `body` на `/cards`.
Что будет получено:
- в Postman:
```json
{
    "message": "[object Object]"
}
```
- в консоли терминала:
```bash
(node:69556) UnhandledPromiseRejectionWarning: ValidationError: card validation failed: owner: Path `owner` is required.
    at new ValidationError (/Users/jmi/work/ya-reviews/15_sprint/node_modules/mongoose/lib/error/validation.js:31:11)
    at model.Document.invalidate (/Users/jmi/work/ya-reviews/15_sprint/node_modules/mongoose/lib/document.js:2481:32)
    at p.doValidate.skipSchemaValidators (/Users/jmi/work/ya-reviews/15_sprint/node_modules/mongoose/lib/document.js:2330:17)
    at /Users/jmi/work/ya-reviews/15_sprint/node_modules/mongoose/lib/schematype.js:1064:9
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
(node:69556) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 5)
```

Тут сразу две ошибки:
- то же самое поведение с `next` (чинится также как и остальные),
- не передается `owner` при создании записи (модель `Card` ожидает, что будет передан `id` пользователя, который хранится в `req.user._id`)

2020-03-04 17:02 UTC, aarefiev commented on controllers/cards.js
> +    .catch(next(new Error500('На сервере произошла ошибка')));
Нужно исправить: при удалении карточки возвращается 500 и ошибка в консоли.
Общее поведение аналогично ошибке при регистрации. Чинится точно также.

Как воспроизвести:
1. Отправить `DELETE` запрос с корректным `id` на `/cards/:id` (где `id` - идентификатор существующей карточки).
Что будет получено:
- в Postman:
```json
{
    "message": "На сервере произошла ошибка"
}
```
- в консоли терминала:
```bash
Error: Карта не найдена
    at /Users/jmi/work/ya-reviews/15_sprint/controllers/cards.js:44:14
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

2020-03-04 17:02 UTC, aarefiev commented on controllers/cards.js
> +          next(new NotFoundError('Это не ваша карта, не может быть удалена'));
Нужно исправить: возвращается 404 при удалении карточки чужого пользователя.
При блокировании доступа нужно отправлять код [403 Forbidden](https://developer.mozilla.org/ru/docs/Web/HTTP/Status/403). Для этого кейса уже есть созданная ошибка:
https://github.com/MaximMaslovVik/15_sprint/blob/edba7f1729b81e64588337a5ebd9ed1fd41c09e4/errors/error_403.js

2020-03-05 04:36 UTC, aarefiev requested changes
С предыдущей итерации осталось 3 ошибки и появилась 1 новая. Все практически около обработки ошибок.

**Нужно исправить:**
1. Централизованный обработчик ошибок отправляет 500 при любых ошибках.
2. При создании карточки возвращается 500 и сообщение об ошибке.
3. При попытке получить данные о несуществующем пользователе возвращается некорректное сообщение.
4. При авторизации возвращается 401 и ошибка в консоли.

2020-03-05 04:36 UTC, aarefiev commented on controllers/users.js
> +    .catch(next(new Error401('Ошибка ввода')));
Нужно исправить: при авторизации возвращается 401 и ошибка в консоли.
Общее поведение аналогично ошибке при регистрации. Чинится точно также.

Как воспроизвести:
1. Отправить `POST` запрос с корректными данными в `body` на `/signin`.
Что будет получено:
- в Postman:
```json
{
    "message": "Ошибка ввода"
}
```
- в консоли терминала:
```bash
(node:69484) UnhandledPromiseRejectionWarning: Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at ServerResponse.setHeader (_http_outgoing.js:523:11)
    at ServerResponse.header (/Users/jmi/work/ya-reviews/15_sprint/node_modules/express/lib/response.js:771:10)
    at ServerResponse.append (/Users/jmi/work/ya-reviews/15_sprint/node_modules/express/lib/response.js:732:15)
    at ServerResponse.res.cookie (/Users/jmi/work/ya-reviews/15_sprint/node_modules/express/lib/response.js:857:8)
    at /Users/jmi/work/ya-reviews/15_sprint/controllers/users.js:55:10
(node:69484) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
```

2020-03-05 04:36 UTC, aarefiev commented on app.js
> +  res.status(500).send({ message: 'На сервере произошла ошибка' });
Нужно исправить: централизованный обработчик ошибок не отправляет 500 при любых ошибках.
Это происходит потому что вместо того, чтобы передавать код и сообщение произошедшей ошибки внутри обработчика принудительно отправляется 500 код и сообщение `{ message: 'На сервере произошла ошибка' }`.

Произошедшая ошибка хранится в `err`. Где:
- `statusCode` - код ошибки,
- `message` - сообщение.

Ранее эта обработка была, про её удаление я не писал:
https://github.com/MaximMaslovVik/15_sprint/blob/edba7f1729b81e64588337a5ebd9ed1fd41c09e4/app.js#L70-L73

2020-03-05 04:36 UTC, aarefiev commented on controllers/users.js
> +        throw new NotFoundError({ message: 'Такого пользователя нет' });
Нужно исправить: при попытке получить данные о несуществующем пользователе возвращается некорректное сообщение.
В Postman:
```json
{
    "message": "[object Object]"
}
```
У класса `NotFoundError` другой интерфейс. Ожидается, что будет передана строка сообщения:
https://github.com/MaximMaslovVik/15_sprint/blob/cbf26c85637aee3245c6ecbfa57af49d8bf2623f/errors/error_not_found.js#L2-L5

2020-03-05 04:36 UTC, aarefiev commented on controllers/cards.js
> +  Card.create({ name, link })
Нужно исправить: при создании карточки возвращается 500 и сообщение об ошибке.
Как воспроизвести:
1. Отправить `POST` запрос с заполненным `body` на `/cards`.
Что будет получено:
- в Postman:
```json
{
    "message": "card validation failed: owner: Path `owner` is required."
}
```

Тут осталась одна ошибка:
- не передается `owner` при создании записи (модель `Card` ожидает, что будет передан `id` пользователя, который хранится в `req.user._id`)
```suggestion
  Card.create({ name, link, owner: req.user._id })
```

2020-03-05 19:02 UTC, aarefiev requested changes
Меня беспокоит, что с прошлой итерации была исправлена только 1 ошибка:
- _при создании карточки возвращается 500 и сообщение об ошибке_

В комментариях к ошибкам всё понятно? Я ниже повторно продублировал список и приложил ссылки на комментарии.

**Нужно исправить:**
1. [Централизованный обработчик ошибок отправляет 500 при любых ошибках.](https://github.com/MaximMaslovVik/15_sprint/pull/1#discussion_r388071674)
2. [При попытке получить данные о несуществующем пользователе возвращается некорректное сообщение.](https://github.com/MaximMaslovVik/15_sprint/pull/1#discussion_r388072198)
3. [При авторизации возвращается 401 и ошибка в консоли.](https://github.com/MaximMaslovVik/15_sprint/pull/1#discussion_r388070804)

2020-03-07 21:53 UTC, MaximMaslovVik commented
> Меня беспокоит, что с прошлой итерации была исправлена только 1 ошибка:
> 
> * _при создании карточки возвращается 500 и сообщение об ошибке_
> 
> В комментариях к ошибкам всё понятно? Я ниже повторно продублировал список и приложил ссылки на комментарии.
> 
> **Нужно исправить:**
> 
> 1. [Централизованный обработчик ошибок отправляет 500 при любых ошибках.](https://github.com/MaximMaslovVik/15_sprint/pull/1#discussion_r388071674)
> 2. [При попытке получить данные о несуществующем пользователе возвращается некорректное сообщение.](https://github.com/MaximMaslovVik/15_sprint/pull/1#discussion_r388072198)
> 3. [При авторизации возвращается 401 и ошибка в консоли.](https://github.com/MaximMaslovVik/15_sprint/pull/1#discussion_r388070804)

не понял нужно вывести ошибку в консолль?

с центральнным обработчиком ошибок не понимаю почему он не работает

2020-03-07 22:05 UTC, MaximMaslovVik commented
> > Меня беспокоит, что с прошлой итерации была исправлена только 1 ошибка:
> > 
> > * _при создании карточки возвращается 500 и сообщение об ошибке_
> > 
> > В комментариях к ошибкам всё понятно? Я ниже повторно продублировал список и приложил ссылки на комментарии.
> > **Нужно исправить:**
> > 
> > 1. [Централизованный обработчик ошибок отправляет 500 при любых ошибках.](https://github.com/MaximMaslovVik/15_sprint/pull/1#discussion_r388071674)
> > 2. [При попытке получить данные о несуществующем пользователе возвращается некорректное сообщение.](https://github.com/MaximMaslovVik/15_sprint/pull/1#discussion_r388072198)
> > 3. [При авторизации возвращается 401 и ошибка в консоли.](https://github.com/MaximMaslovVik/15_sprint/pull/1#discussion_r388070804)
> 
> не понял нужно вывести ошибку в консолль?
> 
> с центральным обработчиком ошибок не понимаю почему он не работает

и в целом почему у меня не работает приложение

2020-03-07 22:51 UTC, MaximMaslovVik commented
> > > Меня беспокоит, что с прошлой итерации была исправлена только 1 ошибка:
> > > 
> > > * _при создании карточки возвращается 500 и сообщение об ошибке_
> > > 
> > > В комментариях к ошибкам всё понятно? Я ниже повторно продублировал список и приложил ссылки на комментарии.
> > > **Нужно исправить:**
> > > 
> > > 1. [Централизованный обработчик ошибок отправляет 500 при любых ошибках.](https://github.com/MaximMaslovVik/15_sprint/pull/1#discussion_r388071674)
> > > 2. [При попытке получить данные о несуществующем пользователе возвращается некорректное сообщение.](https://github.com/MaximMaslovVik/15_sprint/pull/1#discussion_r388072198)
> > > 3. [При авторизации возвращается 401 и ошибка в консоли.](https://github.com/MaximMaslovVik/15_sprint/pull/1#discussion_r388070804)
> > 
> > 
> > не понял нужно вывести ошибку в консолль?
> > с центральным обработчиком ошибок не понимаю почему он не работает
> 
> и в целом почему у меня не работает приложение

https://expressjs.com/en/guide/error-handling.html
 тут пытаюсь понять
но не догогняю

2020-03-07 23:02 UTC, MaximMaslovVik commented
> > > > Меня беспокоит, что с прошлой итерации была исправлена только 1 ошибка:
> > > > 
> > > > * _при создании карточки возвращается 500 и сообщение об ошибке_
> > > > 
> > > > В комментариях к ошибкам всё понятно? Я ниже повторно продублировал список и приложил ссылки на комментарии.
> > > > **Нужно исправить:**
> > > > 
> > > > 1. [Централизованный обработчик ошибок отправляет 500 при любых ошибках.](https://github.com/MaximMaslovVik/15_sprint/pull/1#discussion_r388071674)
> > > > 2. [При попытке получить данные о несуществующем пользователе возвращается некорректное сообщение.](https://github.com/MaximMaslovVik/15_sprint/pull/1#discussion_r388072198)
> > > > 3. [При авторизации возвращается 401 и ошибка в консоли.](https://github.com/MaximMaslovVik/15_sprint/pull/1#discussion_r388070804)
> > > 
> > > 
> > > не понял нужно вывести ошибку в консолль?
> > > с центральным обработчиком ошибок не понимаю почему он не работает
> > 
> > 
> > и в целом почему у меня не работает приложение
> 
> https://expressjs.com/en/guide/error-handling.html
> тут пытаюсь понять
> но не догоняю
https://ru.stackoverflow.com/questions/561232/express-js-%D1%80%D0%BE%D1%83%D1%82%D0%B8%D0%BD%D0%B3-%D0%B8-%D0%BE%D0%B1%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D0%BA%D0%B0-%D0%BE%D1%88%D0%B8%D0%B1%D0%BE%D0%BA

2020-03-09 06:30 UTC, aarefiev commented
@MaximMaslovVik спасибо за вопрос, пишу подробнее про ошибки.
1. [Централизованный обработчик ошибок отправляет 500 при любых ошибках.](https://github.com/MaximMaslovVik/15_sprint/pull/1#discussion_r388071674).
Чтобы в работе был полноценный REST в задании требуется, чтобы при возникновении ошибки был отправлен корректный HTTP код этой ошибки. Например, при попытке зайти на закрытый роут без предварительной авторизации нужно отправить HTTP код 401, что и реализовано:
https://github.com/MaximMaslovVik/15_sprint/blob/cbf26c85637aee3245c6ecbfa57af49d8bf2623f/middlewares/auth.js#L13-L15
Но вот обработчик ошибок вместо того, чтобы отправлять ту ошибку, которая произошла и её код, всегда отправляет 500 и сообщение `{ message: 'На сервере произошла ошибка' }`:
https://github.com/MaximMaslovVik/15_sprint/blob/cbf26c85637aee3245c6ecbfa57af49d8bf2623f/app.js#L70-L73
_подсказка, нужно использовать `err.statusCode` и `err.message` в обработчике ошибок, но не забыть про ситуацию, что обычная ошибка не содержит `statusCode`_
2. [При попытке получить данные о несуществующем пользователе возвращается некорректное сообщение.](https://github.com/MaximMaslovVik/15_sprint/pull/1#discussion_r388072198)
Нужно смотреть на то как реализован конструктор ошибки. Он ожидает, что будет передан один параметр `message`, который и будет текстом ошибки:
https://github.com/MaximMaslovVik/15_sprint/blob/cbf26c85637aee3245c6ecbfa57af49d8bf2623f/errors/error_not_found.js#L2-L3
А вы передаете объект:
https://github.com/MaximMaslovVik/15_sprint/blob/cbf26c85637aee3245c6ecbfa57af49d8bf2623f/controllers/users.js#L41
Места где есть эта ошибка: [раз](https://github.com/MaximMaslovVik/15_sprint/blob/cbf26c85637aee3245c6ecbfa57af49d8bf2623f/controllers/users.js#L16), [два](https://github.com/MaximMaslovVik/15_sprint/blob/cbf26c85637aee3245c6ecbfa57af49d8bf2623f/controllers/users.js#L41), [три](https://github.com/MaximMaslovVik/15_sprint/blob/cbf26c85637aee3245c6ecbfa57af49d8bf2623f/controllers/cards.js#L26). 
3. [При авторизации возвращается 401 и ошибка в консоли](https://github.com/MaximMaslovVik/15_sprint/pull/1#discussion_r388070804).
Здесь проблема в том как происходит обработка ошибки:
https://github.com/MaximMaslovVik/15_sprint/blob/cbf26c85637aee3245c6ecbfa57af49d8bf2623f/controllers/users.js#L63
Нужно вспомнить про `next` и `.catch()` блок. Несколько итераций назад в остальных контроллерах это было исправлено.

2020-03-09 06:31 UTC, aarefiev requested changes
С прошлой итерации ошибки не исправлены.

**Нужно исправить:**
1. [Централизованный обработчик ошибок отправляет 500 при любых ошибках.](https://github.com/MaximMaslovVik/15_sprint/pull/1#discussion_r388071674)
2. [При попытке получить данные о несуществующем пользователе возвращается некорректное сообщение.](https://github.com/MaximMaslovVik/15_sprint/pull/1#discussion_r388072198)
3. [При авторизации возвращается 401 и ошибка в консоли.](https://github.com/MaximMaslovVik/15_sprint/pull/1#discussion_r388070804)

2020-03-10 18:29 UTC, aarefiev requested changes
Отлично, с роутами практически разобрались. Осталось немного причесать. Требования к функционалу и к режиму разработки уже практически выполнены.

**Нужно исправить:**
1. Валидация поля `link` не соответствует схеме модели.
2. При попытке создать пользователя с уже зарегистрированным `email` возвращается 500.

Но эти два пункта еще не все. Большой вопрос - это про публичный сервер. Прямо сейчас он не отвечает на запросы, ни по IP-адресу, ни по доменному имени. К следующей итерации нужно разобраться с публичным сервером и актуализировать адреса. Я очень надеюсь, что на этой неделе я смогу принять этот _pull-request_.

2020-03-10 18:29 UTC, aarefiev commented on routes/cards.js
> +    link: Joi.string().required(),
Нужно исправить: валидация поля `link` не соответствует схеме модели.
В модели `Card` поле `link` ожидается, что это будет не просто строка, а строка формата URL:
https://github.com/MaximMaslovVik/15_sprint/blob/5d5e9a2f50c14679a7121290a01a3d3631ea96cc/models/card.js#L3
Рекомендую использовать встроенный валидатор для указания схемы таких строк [`.uri()`](https://github.com/hapijs/joi/blob/master/API.md#stringurioptions):
```suggestion
    link: Joi.string().uri().required(),
```

2020-03-10 18:29 UTC, aarefiev commented on controllers/users.js
> +      .catch(next);
Нужно исправить: при попытке создать пользователя с уже зарегистрированным `email` возвращается 500. 
Согласно заданию, `email` - это уникальное поле в таблице. С этим все ок. Но не ок с кодом ответа. В REST для ситуаций, когда блокируется создание записи из-за конфликта существует отдельный код - [409 Conflict](https://developer.mozilla.org/ru/docs/Web/HTTP/Status/409).

Я нашел интересную [статью](http://thecodebarbarian.com/mongoose-error-handling.html), в которой расписано как можно ловить подобные ошибки используя возможности `mongoose`. Согласно этой статье нужно создать мидлвару и повесить её выполнение на сохранение записи (также в статье рекомендуют устанавливать не только на сохранение, но и на обновление и вставку нескольких записей):
```js
// models/user.js
function duplicateErrorHandleMiddleware(error, res, next) {
  if (error.name === 'MongoError' && error.code === 11000) {
    next(new Error409(error.toString()));
  } else {
    next();
  }
}

userSchema.post('save', duplicateErrorHandleMiddleware);
userSchema.post('update', duplicateErrorHandleMiddleware);
userSchema.post('findOneAndUpdate', duplicateErrorHandleMiddleware);
userSchema.post('insertMany', duplicateErrorHandleMiddleware);
```
_указанный выше код нужно вставить до экспорта самой модели_

Обращаю внимание, что в коде используется новый модуль ошибки `Error409`. Это класс, аналогичный `Error401`. Его интерфейс и расположение аналогично `Error401`, только статус нужно указать 409. Этот статус впоследствии и будет отправлен клиенту при возникновении ошибки.

2020-03-12 19:19 UTC, aarefiev requested changes
Отлично. По функционалу все. Осталось закрыть с продакшеном, линтингом и игнорированием временных файлов.

**Нужно исправить:**
1. Не происходит обработка запросов сервером, подключаясь по IP-адресу.
2. Не происходит обработка запросов сервером, подключаясь по доменному имени.
3. Ошибки линтинга.
4. Не игнорируется временный файл `error.log`.
5. Не игнорируется временный файл `request.log`.

2020-03-12 19:19 UTC, aarefiev commented on README.md
> +84.201.186.75 Публичный IP
Нужно исправить: не происходит обработка запросов сервером, подключаясь по IP-адресу.
При обращении на любой роут по указанному IP-адресу получаю следующий ответ:
```html
<html>

<head>
	<title>404 Not Found</title>
</head>

<body bgcolor="white">
	<center>
		<h1>404 Not Found</h1>
	</center>
	<hr>
	<center>nginx/1.14.0 (Ubuntu)</center>
</body>

</html>
```

2020-03-12 19:19 UTC, aarefiev commented on README.md
> +max-mesto.ml Cсылка на страницу
Нужно исправить: не происходит обработка запросов сервером, подключаясь по доменному имени.
При обращении на любой роут по указанному доменному имени получаю следующий ответ:
```html
<html>

<head>
	<title>502 Bad Gateway</title>
</head>

<body bgcolor="white">
	<center>
		<h1>502 Bad Gateway</h1>
	</center>
	<hr>
	<center>nginx/1.14.0 (Ubuntu)</center>
</body>

</html>
```

2020-03-12 19:19 UTC, aarefiev commented on request.log
> +{"meta":{"req":{"url":"/users","headers":{"user-agent":"PostmanRuntime/7.22.0","accept":"*/*","cache-control":"no-cache","postman-token":"699584b8-5f23-4f00-94a7-5bbaef5b22bd","host":"localhost:3000"
Нужно исправить: не игнорируется временный файл `request.log`.
По заданию, этот файл записывает входящие соединения. Этот файл является временным, потому что создается только в процессе запуска сервера. Любые временные файлы нужно удалять из репозитория и добавлять их в список игнорирования.

2020-03-12 19:19 UTC, aarefiev commented on error.log
> +{"meta":{"error":{"statusCode":401},"level":"error","message":"uncaughtException: Доступ запрещен. Необходима авторизация\nError: Доступ запрещен. Необходима авторизация\n    at module.exports (C:\\m
Нужно исправить: не игнорируется временный файл `error.log`.
По заданию, этот файл записывает ошибки. Этот файл является временным, потому что создается только в процессе запуска сервера.

2020-03-12 19:19 UTC, aarefiev commented on controllers/cards.js
> +  Card.findById(req.params.cardId)
Нужно исправить: ошибки линтинга.
```bash
/Users/jmi/work/ya-reviews/15_sprint/controllers/cards.js
  23:46  error  Expected to return a value at the end of arrow function  consistent-return
```
```suggestion
  return Card.findById(req.params.cardId)
```

2020-03-12 19:19 UTC, aarefiev commented on middlewares/auth.js
>    next();
Нужно исправить: ошибки линтинга.
```bash
/Users/jmi/work/ya-reviews/15_sprint/middlewares/auth.js
  11:35  error  Expected to return a value at the end of arrow function  consistent-return
```
```suggestion
  return next();
```

2020-03-12 22:34 UTC, MaximMaslovVik commented on README.md
> +max-mesto.ml Cсылка на страницу
привет, локально сервер выдает ошибку, const { requestLogger, errorLogger } = require('./middlewares/logger'); не может найти

2020-03-12 22:34 UTC, MaximMaslovVik commented on README.md
> +max-mesto.ml Cсылка на страницу
как исправить не нашел

2020-03-13 18:56 UTC, MaximMaslovVik commented
для клонирования

2020-03-13 18:56 UTC, closed without merging